apiVersion: v1
kind: Service
metadata:
  name: prediction-api
  labels:
    app: prediction-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080 # The port the service will listen on
      targetPort: 3000 # The port your application listens on in the container
  selector:
    app: prediction-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
  labels:
    app: prediction-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
        - name: prediction-api
          image: luillyfe/prediction-api
          env:
            - name: MODEL_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: model_name
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: api_key
            - name: TODOS_PROMPT
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: todos_prompt
            - name: EXAM_PROMPT
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: exam_prompt
          ports:
            - containerPort: 8080
